import type { Mocks } from "../../models/types/mocks";
import type { Result } from "../../models/types/result";
import type HTMLParser from "../parsers/html-parser";

/** For any feature function that simply fetches data */
interface GetterArgs {
	cookie: string;
	mocks?: Mocks;
	parserConstructor?: typeof HTMLParser;
}

/** The link to be used is defined in `UmisPage` */
export type StaticUmisGetter<TResultType> = (
	arg: GetterArgs,
) => Promise<Result<TResultType, string>>;

/** Requires a link for autogenerated pages like individual semester results */
export type DynamicUmisGetter<TResultType> = (
	arg: GetterArgs & { link: string },
) => Promise<Result<TResultType, string>>;
